### ISSUE TITLE
doesnt work at all?

### ISSUE THREAD

**Issue by TorchedSammy** [oae/kaizoku#123]
### Describe the bug

hi, i got kaizoku on docker and if i try to search for manga with ANY source, it says "no results found" even though i can:
1. go on the site and find the manga
2. run mangal locally and get results

i was trying to search for some specific manga i wanted to read, and then saw the example of bleach doesn't even work.

slightly related, kaizoku should say that a search failed instead of saying there were no results

logs:
```
{"level":30,"time":1692906970760,"pid":298,"hostname":"e8c3e527cbee","msg":"Getting mangal config with following command: mangal config info -j"}
{"level":50,"time":1692906972821,"pid":298,"hostname":"e8c3e527cbee","msg":"Failed to set mangal config. err: Error: Command failed with exit code 1: mangal config set --key mangadex.show_unavailable_chapters --value true\nX open /config/.config/mangal/mangal.toml: permission denied"}
{"level":30,"time":1692906973161,"pid":298,"hostname":"e8c3e527cbee","msg":"Getting mangal config with following command: mangal config info -j"}
{"level":30,"time":1692912587981,"pid":298,"hostname":"e8c3e527cbee","msg":"Get available sources with following command: mangal sources list -r"}
{"level":30,"time":1692912595958,"pid":298,"hostname":"e8c3e527cbee","msg":"Search manga with following command: mangal inline --source Manganato --include-anilist-manga --query gal-sen -j"}
{"level":30,"time":1692912652713,"pid":298,"hostname":"e8c3e527cbee","msg":"Getting mangal config with following command: mangal config info -j"}
{"level":30,"time":1692912653248,"pid":298,"hostname":"e8c3e527cbee","msg":"Getting mangal config with following command: mangal config info -j"}
{"level":30,"time":1692912681732,"pid":298,"hostname":"e8c3e527cbee","msg":"Getting mangal config with following command: mangal config info -j"}
{"level":30,"time":1692912823663,"pid":248,"hostname":"e8c3e527cbee","msg":"> Ready on http://localhost:3000 - env production"}
{"level":30,"time":1692912920259,"pid":248,"hostname":"e8c3e527cbee","msg":"Getting mangal config with following command: mangal config info -j"}
{"level":30,"time":1692912933390,"pid":248,"hostname":"e8c3e527cbee","msg":"Get available sources with following command: mangal sources list -r"}
{"level":30,"time":1692912942565,"pid":248,"hostname":"e8c3e527cbee","msg":"Search manga with following command: mangal inline --source Manganato --include-anilist-manga --query bleach -j"}
{"level":30,"time":1692913002002,"pid":248,"hostname":"e8c3e527cbee","msg":"Search manga with following command: mangal inline --source Manganato --include-anilist-manga --query bleach -j"}
{"level":30,"time":1692913003433,"pid":248,"hostname":"e8c3e527cbee","msg":"Search manga with following command: mangal inline --source Manganato --include-anilist-manga --query bleach -j"}
{"level":30,"time":1692913004734,"pid":248,"hostname":"e8c3e527cbee","msg":"Search manga with following command: mangal inline --source Manganato --include-anilist-manga --query bleach -j"}
{"level":30,"time":1692913005952,"pid":248,"hostname":"e8c3e527cbee","msg":"Search manga with following command: mangal inline --source Manganato --include-anilist-manga --query bleach -j"}
{"level":30,"time":1692913007845,"pid":248,"hostname":"e8c3e527cbee","msg":"Search manga with following command: mangal inline --source Manganato --include-anilist-manga --query bleach -j"}
{"level":30,"time":1692913009401,"pid":248,"hostname":"e8c3e527cbee","msg":"Search manga with following command: mangal inline --source Manganato --include-anilist-manga --query bleach -j"}
{"level":30,"time":1692913011895,"pid":248,"hostname":"e8c3e527cbee","msg":"Search manga with following command: mangal inline --source Manganato --include-anilist-manga --query bleach -j"}
{"level":30,"time":1692913012919,"pid":248,"hostname":"e8c3e527cbee","msg":"Search manga with following command: mangal inline --source Manganato --include-anilist-manga --query bleach -j"}
{"level":50,"time":1692913048763,"pid":248,"hostname":"e8c3e527cbee","msg":"Failed to search manga. err: Error: Command failed with exit code 1: mangal inline --source Mangasee --include-anilist-manga --query bleach -j\nX /config/.config/mangal/sources/Mangasee.lua:46: attempt to index a non-table object(nil) with key 'page'\nstack traceback:\n\t/config/.config/mangal/sources/Mangasee.lua:46: in main chunk\n\t[G]: ?\n[launcher.Browser]2023/08/25 00:37:27 try to find the fastest host to download the browser binary\n[launcher.Browser]2023/08/25 00:37:27 check https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1087031/chrome-linux.zip\n[launcher.Browser]2023/08/25 00:37:27 check https://registry.npmmirror.com/-/binary/chromium-browser-snapshots/Linux_x64/1087031/chrome-linux.zip\n[launcher.Browser]2023/08/25 00:37:27 check https://playwright.azureedge.net/builds/chromium/1087031/chromium-linux-arm64.zip\n[launcher.Browser]2023/08/25 00:37:28 check result: Get \"https://cdn.npmmirror.com/binaries/chromium-browser-snapshots/Linux_x64/1087031/chrome-linux.zip\": context canceled\n[launcher.Browser]2023/08/25 00:37:28 Download: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1087031/chrome-linux.zip"}
{"level":50,"time":1692913050178,"pid":248,"hostname":"e8c3e527cbee","msg":"Failed to search manga. err: Error: Command failed with exit code 1: mangal inline --source Mangasee --include-anilist-manga --query bleach -j\nX /config/.config/mangal/sources/Mangasee.lua:46: attempt to index a non-table object(nil) with key 'page'\nstack traceback:\n\t/config/.config/mangal/sources/Mangasee.lua:46: in main chunk\n\t[G]: ?\n[launcher.Browser]2023/08/25 00:37:29 try to find the fastest host to download the browser binary\n[launcher.Browser]2023/08/25 00:37:29 check https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1087031/chrome-linux.zip\n[launcher.Browser]2023/08/25 00:37:29 check https://registry.npmmirror.com/-/binary/chromium-browser-snapshots/Linux_x64/1087031/chrome-linux.zip\n[launcher.Browser]2023/08/25 00:37:29 check https://playwright.azureedge.net/builds/chromium/1087031/chromium-linux-arm64.zip\n[launcher.Browser]2023/08/25 00:37:30 check result: Get \"https://cdn.npmmirror.com/binaries/chromium-browser-snapshots/Linux_x64/1087031/chrome-linux.zip\": context canceled\n[launcher.Browser]2023/08/25 00:37:30 Download: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1087031/chrome-linux.zip"}
{"level":30,"time":1692913058995,"pid":248,"hostname":"e8c3e527cbee","msg":"Search manga with following command: mangal inline --source Mangapill --include-anilist-manga --query bleach -j"}
```

### Reproduction steps

1. Install Kaizoku with docker compose
2. Try to search for manga
3. See no results found

### Expected behavior

I expect there to be manga results for searches that I *know* are correct

### Additional context

docker-compose.yml is basically default:
```yml
version: '3'

volumes:
  db:
  redis:

services:
  app:
    container_name: kaizoku
    image: ghcr.io/oae/kaizoku:latest
    environment:
      - DATABASE_URL=postgresql://kaizoku:kaizoku@db:5432/kaizoku
      - KAIZOKU_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./data:/data
      - ./configs/kaizoku:/config
      - ./data/logs:/logs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
  db:
    image: postgres:alpine
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kaizoku']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=kaizoku
      - POSTGRES_DB=kaizoku
      - POSTGRES_PASSWORD=kaizoku
    volumes:
      - db:/var/lib/postgresql/data
```
