### ISSUE TITLE
Fresh Docker Install, loads UI but won't load Available Sources

### ISSUE THREAD

**Issue by alejakun** [oae/kaizoku#141]
### Describe the bug

I just installed with the docker image, it seems to work fine, however it does not show anything when trying to add a New Library/Manga in the field Available sources. Checking at the logs it shows the following:

`{"level":50,"time":1696973407106,"pid":308,"hostname":"d12d3bc2e27a","msg":"Failed to get available sources. err: Error: Command failed with exit code 2: mangal sources list -r\npanic: mkdir /config/.config/mangal/sources: permission denied\n\ngoroutine 1 [running]:\ngithub.com/samber/lo.must({0xefeae0, 0xc000476d80}, {0x0, 0x0, 0x0})\n\tgithub.com/samber/lo@v1.37.0/errors.go:53 +0x1f4\ngithub.com/samber/lo.Must0(...)\n\tgithub.com/samber/lo@v1.37.0/errors.go:72\ngithub.com/metafates/mangal/where.mkdir({0xc000265aa0, 0x1e})\n\tgithub.com/metafates/mangal/where/where.go:18 +0x57\ngithub.com/metafates/mangal/where.Sources()\n\tgithub.com/metafates/mangal/where/where.go:39 +0x5b\ngithub.com/metafates/mangal/provider.Customs()\n\tgithub.com/metafates/mangal/provider/provider.go:31 +0x49\ngithub.com/metafates/mangal/cmd.glob..func24.3()\n\tgithub.com/metafates/mangal/cmd/sources.go:67 +0x3b\ngithub.com/metafates/mangal/cmd.glob..func24(0x1d291e0, {0x101d881?, 0x1?, 0x1?})\n\tgithub.com/metafates/mangal/cmd/sources.go:82 +0x3ea\ngithub.com/spf13/cobra.(*Command).execute(0x1d291e0, {0xc0004a0640, 0x1, 0x1})\n\tgithub.com/spf13/cobra@v1.6.1/command.go:920 +0x847\ngithub.com/spf13/cobra.(*Command).ExecuteC(0x1d2a040)\n\tgithub.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\tgithub.com/spf13/cobra@v1.6.1/command.go:968\ngithub.com/metafates/mangal/cmd.Execute()\n\tgithub.com/metafates/mangal/cmd/root.go:112 +0x7a\nmain.main()\n\tgithub.com/metafates/mangal/main.go:13 +0x4d\nMangadex\nManganelo\nManganato\nMangapill"}
`

### Reproduction steps

Fresh install with the following docker compose:

```
  kaizoku:
    image: ghcr.io/oae/kaizoku:latest
    container_name: kaizoku
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    ports:
      - "$KAIZOKU_PORT:3000"
    environment:
      - DATABASE_URL=postgresql://kaizoku:kaizoku@kaizoku_db:5432/kaizoku
      - KAIZOKU_PORT=3000
      - REDIS_HOST=kaizoku_redis
      - REDIS_PORT=6379
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $PWD/kaizoku/config:/config
      - $PWD/kaizoku/data:/data
      - $PWD/kaizoku/logs:/logs
    depends_on:
      kaizoku_db:
        condition: service_healthy

  kaizoku_redis:
    image: redis:7-alpine
    container_name: kaizoku_redis
    user: "$PUID:$PGID"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    volumes:
      - $PWD/kaizoku/redis:/data
  kaizoku_db:
    image: postgres:15-alpine
    container_name: kaizoku_db
    user: "$PUID:$PGID"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kaizoku']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=kaizoku
      - POSTGRES_DB=kaizoku
      - POSTGRES_PASSWORD=kaizoku
    volumes:
      - $PWD/kaizoku/postgres:/var/lib/postgresql/data
```

### Expected behavior

Should load something for Available sources.
