### ISSUE TITLE
Kaizoku can't create library or make directories 

### ISSUE THREAD

**Issue by manchesterca** [oae/kaizoku#143]
### Describe the bug

Docker install on OSX, on initial install to create a library, I'll get the following error when attempting to make /data. There's no directory browsing on this field, it's just asking for a direct path.

`Failed to create library. TRPCClientError: ENOENT: no such file or directory, mkdir '/data'`

docker-compose.yml below, the volume paths are local to try and diagnose, but eventually they'll go to my NAS('/Volumes/NAS\ Storage/Komga').

```
version: '3'

volumes:
  db:
  redis:

services:
  app:
    container_name: kaizoku
    image: ghcr.io/oae/kaizoku:latest
    environment:
      - DATABASE_URL=postgresql://kaizoku:kaizoku@db:5432/kaizoku
      - KAIZOKU_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PUID=501
      - PGID=80
      - TZ=America/Los_Angeles
    networks:
      - mynetwork
    volumes:
      - '/Users/manchesterca/Desktop/Komga:/app/manga'
      - '/Users/manchesterca/Desktop/Komga:/data'
      - '/Users/manchesterca/Desktop/Komga:/config'
      - '/Users/manchesterca/Desktop/Komga:/logs'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
  db:
    image: postgres:alpine
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kaizoku']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=kaizoku
      - POSTGRES_DB=kaizoku
      - POSTGRES_PASSWORD=kaizoku
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT:-5432}:5432"
```

### Reproduction steps

1. launch with above fresh docker-compose.yml
2. goto http://localhost:3000/
3. Click 'create library'
4. type '/data' (as shown by the example input).
5. observe error message.

### Expected behavior

should bind and makdir as expected.

### Additional context

any help appreciated here, just can't seem to get this to work!
