### ISSUE TITLE
[Issue] Postgres authentication issues

### ISSUE THREAD

**Issue by axsddlr** [oae/kaizoku#20]
Following README docker-compose

## Logs

# DB container
```
2022-10-28 18:02:31.577 UTC [823] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
2022-10-28 18:02:36.057 UTC [831] FATAL:  password authentication failed for user "kaizoku"
```

# Main app container
```
[14:04:27.002] ERROR (4491): 
Invalid `prisma.manga.findMany()` invocation:
Authentication failed against database server at `db`, the provided database credentials for `kaizoku` are not valid.
Please make sure to provide valid database credentials for the database server at `db`.
```

**Comment by oae** [comment]
Can you share your exact docker-compose file? Because I am not able to reproduce this.

**Comment by axsddlr** [comment]
> Can you share your exact docker-compose file? Because I am not able to reproduce this with the example inside README.

```
version: '3'

volumes:
  db:
  redis:

services:
  app:
    container_name: kaizoku
    image: ghcr.io/oae/kaizoku:latest
    environment:
      - DATABASE_URL=postgresql://kaizoku:kaizoku@db:5432/kaizoku
      - KAIZOKU_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/node1/Manga:/data
      - /home/node1/docker_configs/kaizoku/config:/config
      - /home/node1/docker_configs/kaizoku/logs:/logs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3011:3000'
  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
  db:
    image: postgres:alpine
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kaizoku']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=kaizoku
      - POSTGRES_DB=kaizoku
      - POSTGRES_PASSWORD=kaizoku
    volumes:
      - db:/var/lib/postgresql/data
```
